
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { AudioPlayer } from "@/components/AudioPlayer";
import Script from 'next/script';
import { MusicPlayer } from '@/components/MusicPlayer';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <h1>audio file visualizer</h1>

        <MusicPlayer
          src={'/audio/piano.mp3'}
          title={'React Song'}
          artist={'React Artst'}
          controls={true}
          isPreload={true}
          isLoop={false}
          xorigin={'anonymous'}
        />

        {/* <AudioPlayer /> */}
        {/* <MusicPlayer /> */}

        {/* <MusicPlayer /> */}

        
      </main>
      
      <footer>
        <span>williamusic</span>
      </footer>
    </>
  )
}